-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2014.3 (64-bit) Schlumberger
-- User name   : fonsecarm
-- Date        : Friday, December 23 2016 13:00:41
-- Project     : Benchmark_Truth_16122016.pet
-- Generated ]

FILLEPS                                -- Generated : Petrel

PVTW                                   -- Generated : Petrel
           280       1.0132  3.9795E-005      0.39851            0 /

PVDO                                   -- Generated : Petrel
            80       1.1069       2.5171
        94.211       1.1038       2.5676
        108.42       1.1016       2.6272
        122.63       1.0999       2.6951
        136.84       1.0985       2.7708
        151.05       1.0974       2.8538
        165.26       1.0965       2.9436
        179.47       1.0957       3.0401
        193.68       1.0951       3.1428
        207.89       1.0945       3.2517
        222.11        1.094       3.3666
        236.32       1.0936       3.4871
        250.53       1.0932       3.6133
        264.74       1.0928       3.7448
        278.95       1.0925       3.8817
        293.16       1.0923       4.0236
        307.37        1.092       4.1705
        321.58       1.0918       4.3221
        335.79       1.0916       4.4782
  /

DENSITY                                -- Generated : Petrel
        850       1020.3      0.81172 /

ROCKOPTS                               -- Generated : Petrel
  1* 1* ROCKNUM /

ROCK                                   -- Generated : Petrel
      280.0000  1.4234E-005 /

