WCONINJE
'INJECT1'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT2'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT3'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT4'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT5'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT6'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT7'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT8'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
/

TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
   
WCONPROD
    'PROD1' 'OPEN' 'BHP' 5*  395/
    'PROD3' 'OPEN' 'BHP' 5*  395/
    'PROD2' 'OPEN' 'BHP' 5*  395/
    'PROD4' 'OPEN' 'BHP' 5*  395/
/

WCONINJE
'INJECT1'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT2'	'WATER'	'OPEN'	'RATE'	60.5 1* 420/
'INJECT3'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT4'	'WATER'	'OPEN'	'RATE'	120.5 1* 420/
'INJECT5'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT6'	'WATER'	'OPEN'	'RATE'	60.5 1* 420/
'INJECT7'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT8'	'WATER'	'OPEN'	'RATE'	60.5 1* 420/
/

TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
WCONPROD
    'PROD1' 'OPEN' 'BHP' 5*  395/
    'PROD3' 'OPEN' 'BHP' 5*  395/
    'PROD2' 'OPEN' 'BHP' 5*  395/
    'PROD4' 'OPEN' 'BHP' 5*  395/
/

WCONINJE
'INJECT1'	'WATER'	'OPEN'	'RATE'	100.5 1* 420/
'INJECT2'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT3'	'WATER'	'OPEN'	'RATE'	100.5 1* 420/
'INJECT4'	'WATER'	'OPEN'	'RATE'	60.5 1* 420/
'INJECT5'	'WATER'	'OPEN'	'RATE'	100.5 1* 420/
'INJECT6'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT7'	'WATER'	'OPEN'	'RATE'	100.5 1* 420/
'INJECT8'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
/
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /   
WCONPROD
    'PROD1' 'OPEN' 'BHP' 5*  375/
    'PROD3' 'OPEN' 'BHP' 5*  400/
    'PROD2' 'OPEN' 'BHP' 5*  395/
    'PROD4' 'OPEN' 'BHP' 5*  375/
/
WCONINJE
'INJECT1'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT2'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT3'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT4'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT5'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT6'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT7'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
'INJECT8'	'WATER'	'OPEN'	'RATE'	79.5 1* 420/
/  
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
TSTEP
   30 /
END

